{% set name = "pytest_parallel_mpi" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onera/pytest_parallel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 666ecb0d4fbdfe07b25dca538e0dd105caf7cb49c52f51cf459531b4a37801f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pytest ==6.2.5
    - python >=3.8
    - mpi4py
    - numpy

test:
  imports:
    - pytest_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onera/pytest_parallel
  summary: a pytest plugin to manage test in distributed way with MPI Standard
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MicK7
